name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install chromedriver-autoinstaller selenium pyvirtualdisplay

    - name: Build Docker image
      run: docker build -t ci_cd .

    - name: Installed package list
      run: apt list --installed
    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable
    - name: Remove default Chromium
      run: sudo apt purge chromium-browser
    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser
    - name: Install all necessary packages
      run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
    - name: Run the scraping script
      run: python test_endtoend_app.py

    - name: Test with pytest
      run: |
        docker run ci_cd pytest

    - name: Running unit tests
      run: |
        docker run ci_cd python /app/test_app.py
